apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram2-reverseproxy
  name: udagram2-reverseproxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: udagram2-reverseproxy
